### PR TITLE
added download tokens in zip file

### PR DESCRIPTION
**Pull request by facupascale**

### CODE REVIEW

**Comment by apresmoi** [comment]
Hi @facupascale ! Thanks for the PR.

May we change the name of the files to the following?

`Css.css` > `styles.css`
`Scss.css` > `styles.scss`
`Dsp.json` > `dsp.json`
`Theo.json` > `theo.json`
`W3C.json` > `dtcg.json`

**Review by apresmoi — CHANGES_REQUESTED** [review]
Hi @facupascale ! Thanks for the PR.

May we change the name of the files to the following?

`Css.css` > `styles.css`
`Scss.css` > `styles.scss`
`Dsp.json` > `dsp.json`
`Theo.json` > `theo.json`
`W3C.json` > `dtcg.json`

Also, is there a way that we could format the files ? I believe the CSS file isn't formatted properly.

**Comment by facupascale** [comment]
> 

I changed the file's name but I think there isnt a way to format the files. The function save it the same that the platform shows

**Review by apresmoi — CHANGES_REQUESTED** [review]
There is something weird happening with Theo's file name, it is showing as `theo.JSON`

**Review by apresmoi — APPROVED** [review]

**Pull request merged**
